apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    name: myapp
spec:
  containers:
  - name: myapp
    image: nginx:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
    volumeMounts:
      - mountPath: "/aulafs02"
        name: volumeteste
  volumes:
    - name: volumeteste
      persistentVolumeClaim:
        claimName: mypvc