apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: frontend
  labels:
    app: guestbook
    tier: frontend
    aula: fs02
spec:
  # modify replicas according to your case
  replicas: 3
  template:
    metadata:
      labels:
        app: guestbook
        tier: frontend
    spec:
      containers:
      - name: apache
        image: httpd
        ports: 
          - containerPort: 80
  selector:
    matchLabels:
      tier: frontend