apiVersion: apps/v1
kind: Deployment
metadata:
  name: depl-01
spec:
  template:
    metadata:
      labels:
        app: depl-01
    spec:
      containers:
      - name: depl-01
        image: nginx:stable
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
  replicas: 8
  selector:
    matchLabels:
      app: depl-01